/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConferenciaRouteImport } from './routes/conferencia'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FiadoRouteImport } from './routes/fiado'
import { Route as FiadoClienteRouteImport } from './routes/fiado.cliente'
import { Route as FiadoCustomerRouteImport } from './routes/fiado.$customer'
import { Route as GerenciaRouteImport } from './routes/gerencia'
import { Route as RecebimentoRouteImport } from './routes/recebimento'
import { Route as VendasRouteImport } from './routes/vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenciaRoute = ConferenciaRouteImport.update({
  id: '/conferencia',
  path: '/conferencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FiadoCustomerRoute = FiadoCustomerRouteImport.update({
  id: '/fiado/$customer',
  path: '/fiado/$customer',
  getParentRoute: () => rootRouteImport,
} as any)
const FiadoClienteRoute = FiadoClienteRouteImport.update({
  id: '/fiado/cliente',
  path: '/fiado/cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const FiadoRoute = FiadoRouteImport.update({
  id: '/fiado',
  path: '/fiado',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciaRoute = GerenciaRouteImport.update({
  id: '/gerencia',
  path: '/gerencia',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoRoute = RecebimentoRouteImport.update({
  id: '/recebimento',
  path: '/recebimento',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conferencia': typeof ConferenciaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/fiado/$customer': typeof FiadoCustomerRoute
  '/fiado/cliente': typeof FiadoClienteRoute
  '/fiado': typeof FiadoRoute
  '/gerencia': typeof GerenciaRoute
  '/recebimento': typeof RecebimentoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conferencia': typeof ConferenciaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/fiado/$customer': typeof FiadoCustomerRoute
  '/fiado/cliente': typeof FiadoClienteRoute
  '/fiado': typeof FiadoRoute
  '/gerencia': typeof GerenciaRoute
  '/recebimento': typeof RecebimentoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conferencia': typeof ConferenciaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/fiado/$customer': typeof FiadoCustomerRoute
  '/fiado/cliente': typeof FiadoClienteRoute
  '/fiado': typeof FiadoRoute
  '/gerencia': typeof GerenciaRoute
  '/recebimento': typeof RecebimentoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conferencia'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/fiado/$customer'
    | '/fiado/cliente'
    | '/fiado'
    | '/gerencia'
    | '/recebimento'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conferencia'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/fiado/$customer'
    | '/fiado/cliente'
    | '/fiado'
    | '/gerencia'
    | '/recebimento'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/conferencia'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/fiado/$customer'
    | '/fiado/cliente'
    | '/fiado'
    | '/gerencia'
    | '/recebimento'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConferenciaRoute: typeof ConferenciaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRoute
  FiadoCustomerRoute: typeof FiadoCustomerRoute
  FiadoClienteRoute: typeof FiadoClienteRoute
  FiadoRoute: typeof FiadoRoute
  GerenciaRoute: typeof GerenciaRoute
  RecebimentoRoute: typeof RecebimentoRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferencia': {
      id: '/conferencia'
      path: '/conferencia'
      fullPath: '/conferencia'
      preLoaderRoute: typeof ConferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiado/$customer': {
      id: '/fiado/$customer'
      path: '/fiado/$customer'
      fullPath: '/fiado/$customer'
      preLoaderRoute: typeof FiadoCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiado/cliente': {
      id: '/fiado/cliente'
      path: '/fiado/cliente'
      fullPath: '/fiado/cliente'
      preLoaderRoute: typeof FiadoClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiado': {
      id: '/fiado'
      path: '/fiado'
      fullPath: '/fiado'
      preLoaderRoute: typeof FiadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencia': {
      id: '/gerencia'
      path: '/gerencia'
      fullPath: '/gerencia'
      preLoaderRoute: typeof GerenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento': {
      id: '/recebimento'
      path: '/recebimento'
      fullPath: '/recebimento'
      preLoaderRoute: typeof RecebimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConferenciaRoute: ConferenciaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  EstoqueRoute: EstoqueRoute,
  FiadoCustomerRoute: FiadoCustomerRoute,
  FiadoClienteRoute: FiadoClienteRoute,
  FiadoRoute: FiadoRoute,
  GerenciaRoute: GerenciaRoute,
  RecebimentoRoute: RecebimentoRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
