/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConferenciaRouteImport } from './routes/conferencia'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as GerenciaRouteImport } from './routes/gerencia'
import { Route as RecebimentoRouteImport } from './routes/recebimento'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenciaRoute = ConferenciaRouteImport.update({
  id: '/conferencia',
  path: '/conferencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const GerenciaRoute = GerenciaRouteImport.update({
  id: '/gerencia',
  path: '/gerencia',
  getParentRoute: () => rootRouteImport,
} as any)
const RecebimentoRoute = RecebimentoRouteImport.update({
  id: '/recebimento',
  path: '/recebimento',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conferencia': typeof ConferenciaRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/gerencia': typeof GerenciaRoute
  '/recebimento': typeof RecebimentoRoute
  '/vendas': typeof VendasRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conferencia': typeof ConferenciaRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/gerencia': typeof GerenciaRoute
  '/recebimento': typeof RecebimentoRoute
  '/vendas': typeof VendasRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conferencia': typeof ConferenciaRoute
  '/dashboard': typeof DashboardRoute
  '/estoque': typeof EstoqueRoute
  '/gerencia': typeof GerenciaRoute
  '/recebimento': typeof RecebimentoRoute
  '/vendas': typeof VendasRoute
  '/configuracoes': typeof ConfiguracoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conferencia'
    | '/dashboard'
    | '/estoque'
    | '/gerencia'
    | '/recebimento'
    | '/vendas'
    | '/configuracoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conferencia'
    | '/dashboard'
    | '/estoque'
    | '/gerencia'
    | '/recebimento'
    | '/vendas'
    | '/configuracoes'
  id:
    | '__root__'
    | '/'
    | '/conferencia'
    | '/dashboard'
    | '/estoque'
    | '/gerencia'
    | '/recebimento'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConferenciaRoute: typeof ConferenciaRoute
  DashboardRoute: typeof DashboardRoute
  EstoqueRoute: typeof EstoqueRoute
  GerenciaRoute: typeof GerenciaRoute
  RecebimentoRoute: typeof RecebimentoRoute
  VendasRoute: typeof VendasRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferencia': {
      id: '/conferencia'
      path: '/conferencia'
      fullPath: '/conferencia'
      preLoaderRoute: typeof ConferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerencia': {
      id: '/gerencia'
      path: '/gerencia'
      fullPath: '/gerencia'
      preLoaderRoute: typeof GerenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recebimento': {
      id: '/recebimento'
      path: '/recebimento'
      fullPath: '/recebimento'
      preLoaderRoute: typeof RecebimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConferenciaRoute: ConferenciaRoute,
  DashboardRoute: DashboardRoute,
  EstoqueRoute: EstoqueRoute,
  GerenciaRoute: GerenciaRoute,
  RecebimentoRoute: RecebimentoRoute,
  VendasRoute: VendasRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
